#!/usr/bin/env php
<?php
require_once __DIR__.'/Parser.php';

class EnvironmentPseudoArray implements ArrayAccess
{
    public function offsetGet($key)
    {
        return getenv($key);
    }

    public function offsetSet($key, $value)
    {
        throw new Exception('nope');
    }

    public function offsetUnset($key)
    {
        throw new Exception('nope');
    }

    public function offsetExists($key)
    {
        return getenv($key) !== false;
    }
}

$config = Toml\Parser::fromFile(__DIR__.'/values.toml');
$config['env'] = new EnvironmentPseudoArray();
$input = file_get_contents('php://stdin');
$output = $input;
$opening = '«';
$closing = '»';

for ($offset = strpos($output, $opening); $offset !== false; $offset = strpos($output, $opening)) {
    $endOffset = strpos($output, $closing, $offset);
    $expression = substr($output, $offset + strlen($opening), $endOffset - $offset - strlen($opening));
    $expression = trim($expression);
    $output = substr_replace($output, find_in_config($expression, $config), $offset, $endOffset - $offset + 2);
}

echo $output;

function find_in_config($selector, $config)
{
    $value = '';
    $chunks = explode('.', $selector);
    $value = $config;
    foreach ($chunks as $chunk) {
        if (!isset($value[$chunk])) {
            fprintf(STDERR, "error: value %s not defined\n", $selector);
            exit(1);
        }
        $value = $value[$chunk];
    }

    return $value;
}

function get($array, $key, $default = null)
{
    if (array_key_exists($key, $array)) {
        return $array[$key];
    }

    return $default;
}
