[colors]
	darkblack = "#070707"
	black = "#151515"
	red = "#fb9fb1"
	green = "#acc267"
	yellow = "#ddb26f"
	blue = "#6fc2ef"
	magenta = "#e1a3ee"
	cyan = "#12cfc0"
	silver = "#d0d0d0"
	gray = "#505050"
	white = "#f5f5f5"
	orange = "#eda987"
	brightorange = "#deaf8f"
	darkergray = "#202020"
	darkgray = "#303030"
	brightgray = "#b0b0b0"
	brightergray = "#e0e0e0"

[fonts]
	terminal = "xft:Iosevka:pixelsize=14"
# vim: noet
