[colors]
	darkblack = "#070707"
	black = "#151515"
	red = "#fb9fb1"
	green = "#acc267"
	yellow = "#ddb26f"
	blue = "#6fc2ef"
	magenta = "#e1a3ee"
	cyan = "#12cfc0"
	silver = "#d0d0d0"
	gray = "#505050"
	white = "#f5f5f5"
	orange = "#eda987"
	brightorange = "#deaf8f"
	darkergray = "#202020"
	darkgray = "#303030"
	brightgray = "#a0a0a0"
	brightergray = "#e0e0e0"

[fonts]
	terminal = "xft:D2Coding Powerline:pixelsize=14, xft:Iosevka:pixelsize=14"

[interface]
	font-name = "Clear Sans"
	font-size = 10
	gtk2-theme = "Plano"
	gtk3-theme = "Zukitre"
	icon-theme = "Elementary"

[paths]
	commands = "/home/og/commands"
	themes = "/run/current-system/sw/share/themes"
	icons = "/run/current-system/sw/share/icons"

# vim: noet
